Repository mkm99/TeamProject_StatsCalculator, pull requests merged in 2020-03, with the labels that each got.

#37 Fix: found error naming module (findSampleSizeUnknownPopulation) bein…
  Tests/test_population_sampling.py
Labels: bug

#36 Task: created a empty list test for random number generator for rando…
  RandomGenerator/random_list.py
Labels: enhancement

#38 Fix: N_numbers_from_list_seed.py PickNumberSeed class fixed check ve…
  RandomGenerator/N_numbers_from_list_seed.py
Labels: bug

#39 Task: Added exception for empty list and test for it in test_random.py
  RandomGenerator/N_numbers_from_list.py
  RandomGenerator/N_numbers_from_list_seed.py
  RandomGenerator/random_list.py
  Tests/test_random.py
Labels: documentation

#42 Task: created .md file w/ all operations and formulas
  operations.md
Labels: documentation
